name: pub_release
version: 3.0.0
homepage: https://github.com/bsutton/pub_release
description: Automates the release of a dart package to pub.dev including running dartfmt, creating a git tag, incrementing the packages version no. and pushing the package to pub.dev.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  dcli: ^1.3.0
  github: ^8.0.1
  meta: ^1.3.0
  mime: ^1.0.0
  pub_semver: ^2.0.0
  settings_yaml: ^3.0.1
dev_dependencies: 
  dependency_validator: ^3.0.0
  lint: ^1.5.1
  pubspec: ^2.0.1
  test: ^1.16.2
  
dependency_overrides: 
  cli_script: 
    path: ../dart_cli_script
  dcli:
    path: ../dcli
executables: 
  pub_release: 
  github_release: 
  github_workflow_release: 
