name: pub_release
version: 8.0.1
homepage: https://github.com/bsutton/pub_release
documentation: https://pubrelease.noojee.dev/
description: Automates the release of a dart package to pub.dev including running dartfmt, creating a git tag, incrementing the packages version no. and pushing the package to pub.dev.
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  dcli: ^1.33.0
  github: ^9.4.0
  meta: ^1.3.0
  mime: ^1.0.0
  pub_semver: ^2.1.0
  pubspec2: ^2.4.1
  settings_yaml: ^3.0.6
dev_dependencies: 
  dependency_validator: ^3.0.0
  lint_hard: ^2.0.0
  test: ^1.16.2
dependency_overrides: 
  dcli: 
    path: ../dcli/dcli
executables: 
  pub_release: 
  github_release: 
  github_workflow_release: 
platforms: 
  linux: 
  windows: 
  macos: 
