name: pub_release
version: 9.3.0
homepage: https://github.com/bsutton/pub_release
documentation: https://pubrelease.noojee.dev/
description: Automates the release of a dart package to pub.dev including running dartfmt, creating a git tag, incrementing the packages version no. and pushing the package to pub.dev.
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  args: ^2.3.1
  dcli: ^3.2.0-alpha.3
  dcli_core: ^3.2.1
  github: ^9.4.0
  meta: ^1.3.0
  mime: ^1.0.0
  path: ^1.8.3
  pub_semver: ^2.1.0
  pubspec_manager: ^1.0.0-alpha.11
  settings_yaml: ^7.0.0
dev_dependencies: 
  dependency_validator: ^3.0.0
  lint_hard: ^4.0.0
  test: ^1.16.2
executables: 
  pub_release: 
  github_release: 
  github_workflow_release: 
platforms: 
  linux: 
  windows: 
  macos: 
