name: pub_release
version: 9.0.0-beta.1
homepage: https://github.com/bsutton/pub_release
documentation: https://pubrelease.noojee.dev/
description: Automates the release of a dart package to pub.dev including running dartfmt, creating a git tag, incrementing the packages version no. and pushing the package to pub.dev.
environment: 
  sdk: '>=2.19.0-444.2.beta <4.0.0'
dependencies: 
  dcli: ^2.0.0-beta.1
  github: ^9.4.0
  meta: ^1.3.0
  mime: ^1.0.0
  pub_semver: ^2.1.0
  pubspec2: ^2.4.1
  settings_yaml: ^5.0.0
dev_dependencies: 
  dependency_validator: ^3.0.0
  lint_hard: ^3.0.0-beta.4
  test: ^1.16.2
executables: 
  pub_release: 
  github_release: 
  github_workflow_release: 
platforms: 
  linux: 
  windows: 
  macos: 
