name: xxxxx_top
description: A simple command-line application.
homepage: https://top.home.com
environment: 
  sdk: '>=2.19.0-444.2.beta <4.0.0'
dependencies: 
  xxxxx_bottom: ^2.0.0
  xxxxx_middle: ^1.0.0
dev_dependencies: 
  lint_hard: ^3.0.0-beta.4
dependency_overrides: 
  xxxxx_bottom: 
    path: ../bottom
  xxxxx_middle: 
    path: ../middle

executables: 
  top: top
