name: xxxxx_bottom
version: 1.0.3
homepage: http://home.com/home
description: A simple command-line application.
environment: 
  sdk: '>=2.10.0 <3.0.0'
dev_dependencies: 
  pedantic: ^1.9.0
  test: ^1.0.0
