name: xxxxx_middle
description: A simple command-line application.
homepage: https://test.home.com
version: 1.0.2
environment: 
  sdk: '>=2.19.0 <4.0.0'
dependencies: 
  xxxxx_bottom: ^2.0.0
dev_dependencies: 
  lint_hard: ^3.0.0
dependency_overrides: 
  xxxxx_bottom: 
    path: ../bottom
