name: middle
description: A simple command-line application.
environment: 
  sdk: '>=2.10.0 <3.0.0'
dependencies: 
  bottom: ^2.0.0
dev_dependencies: 
  pedantic: ^1.9.0
dependency_overrides: 
  bottom: 
    path: ../bottom
